### ISSUE TITLE
[question] what is the reason to manually list maven deps?

### ISSUE THREAD

**Issue by sblantipodi** [flathub/es.estoes.wallpaperDownloader#18]
I'm sorry if I quote you @guihkx 
but I would like to understand why Flathub is not considering that Java doesn't works that way.

what is the added value in manually adding the maven deps here?
listing hundred of deps for a second time, outside of the pom.xml is considered better?

a GitHub CI can build your app with maven as it should be built, what is the added value here?

in that way you could even build your app with jpackage in order to use the exact runtime you need without the needs of the entire JDK and without the needs for a java runtime extension.

in addition, Java is interpreted language, you are not linking anything, building two times the same things brings no benefit.

I just want to understand what is the reasoning here because I feel that I'm missing something.

**Comment by guihkx** [comment]
Hopefully all your questions were answered... Closing.
